spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: default
    include: test
  datasource:
    url: jdbc:mysql://localhost:3306/weatherDB?serverTimezone=Asia/Seoul
    username: hayan
    password: hayan123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
